-- Query to convert the TEDS numeric codes to human readable format and load
-- the data in to a new table.  Must have run all the code in codebook_tables.sql first.
-- This query differs from the query found in TEDS_DOH_conversion.sql by:
--   this one uses the original column names from samhsa, the other changes the column names to match DOH.
--   this one has all the states and the other strips out any non-Hawaii entries.
create table TEDS_A2
select
  TEDS_A.ADMYR, 
  TEDS_A.CASEID,
  TEDS_A.CBSA2010,
  TEDS_XWALK_STFIPS.value as STFIPS,
  TEDS_XWALK_EDUC.value as EDUC,
  TEDS_XWALK_MARSTAT.value as MARSTAT,
  TEDS_XWALK_SERVICES.value as SERVICES,
  TEDS_XWALK_DETCRIM.value as DETCRIM,
  TEDS_XWALK_NOPRIOR.value as NOPRIOR,
  TEDS_XWALK_PSOURCE.value as PSOURCE, 
  TEDS_XWALK_ARRESTS.value as ARRESTS,
  TEDS_XWALK_EMPLOY.value as EMPLOY,
  TEDS_XWALK_METHUSE.value as METHUSE,
  TEDS_XWALK_PSYPROB.value as PSYPROB,
  TEDS_XWALK_PREG.value as PREG,
  TEDS_XWALK_GENDER.value as GENDER,
  TEDS_XWALK_VET.value as VET,
  TEDS_XWALK_LIVARAG.value as LIVARAG,
  TEDS_XWALK_DAYWAIT.value as DAYWAIT,
  TEDS_XWALK_DSMCRIT.value as DSMCRIT,
  TEDS_XWALK_AGE.value as AGE,
  TEDS_XWALK_RACE.value as RACE,
  TEDS_XWALK_ETHNIC.value as ETHNIC,
  TEDS_XWALK_DETNLF.value as DETNLF,
  TEDS_XWALK_PRIMINC.value as PRIMINC,
  TEDS_XWALK_SUB1.value as SUB1,
  TEDS_XWALK_SUB2.value as SUB2,
  TEDS_XWALK_SUB3.value as SUB3,
  TEDS_XWALK_ROUTE1.value as ROUTE1,
  TEDS_XWALK_ROUTE2.value as ROUTE2,
  TEDS_XWALK_ROUTE3.value as ROUTE3,
  TEDS_XWALK_FREQ1.value as FREQ1,
  TEDS_XWALK_FREQ2.value as FREQ2,
  TEDS_XWALK_FREQ3.value as FREQ3,
  TEDS_XWALK_FRSTUSE1.value as FRSTUSE1,
  TEDS_XWALK_FRSTUSE2.value as FRSTUSE2,
  TEDS_XWALK_FRSTUSE3.value as FRSTUSE3,
  TEDS_XWALK_HLTHINS.value as HLTHINS,
  TEDS_XWALK_PRIMPAY.value as PRIMPAY,
  TEDS_XWALK_FREQ_ATND_SELF_HELP.value as FREQ_ATND_SELF_HELP,
  TEDS_XWALK_ALCFLG.value as ALCFLG,
  TEDS_XWALK_COKEFLG.value as COKEFLG,
  TEDS_XWALK_MARFLG.value as MARFLG,
  TEDS_XWALK_HERFLG.value as HERFLG,
  TEDS_XWALK_METHFLG.value as METHFLG,
  TEDS_XWALK_OPSYNFLG.value as OPSYNFLG,
  TEDS_XWALK_PCPFLG.value as PCPFLG,
  TEDS_XWALK_HALLFLG.value as HALLFLG,
  TEDS_XWALK_MTHAMFLG.value as MTHAMFLG,
  TEDS_XWALK_AMPHFLG.value as AMPHFLG,
  TEDS_XWALK_STIMFLG.value as STIMFLG,
  TEDS_XWALK_BENZFLG.value as BENZFLG,
  TEDS_XWALK_TRNQFLG.value as TRNQFLG,
  TEDS_XWALK_BARBFLG.value as BARBFLG,
  TEDS_XWALK_SEDHPFLG.value as SEDHPFLG,
  TEDS_XWALK_INHFLG.value as INHFLG,
  TEDS_XWALK_OTCFLG.value as OTCFLG,
  TEDS_XWALK_OTHERFLG.value as OTHERFLG,
  TEDS_XWALK_DIVISION.value as DIVISION,
  TEDS_XWALK_REGION.value as REGION,
  TEDS_XWALK_IDU.value as IDU,
  TEDS_XWALK_ALCDRUG.value as ALCDRUG
from 
  TEDS_A
  LEFT JOIN TEDS_XWALK_STFIPS ON TEDS_A.STFIPS = TEDS_XWALK_STFIPS.id 
  LEFT JOIN TEDS_XWALK_EDUC ON TEDS_A.EDUC = TEDS_XWALK_EDUC.id
  LEFT JOIN TEDS_XWALK_MARSTAT ON TEDS_A.MARSTAT = TEDS_XWALK_MARSTAT.id
  LEFT JOIN TEDS_XWALK_SERVICES ON TEDS_A.SERVICES = TEDS_XWALK_SERVICES.id
  LEFT JOIN TEDS_XWALK_DETCRIM ON TEDS_A.DETCRIM = TEDS_XWALK_DETCRIM.id
  LEFT JOIN TEDS_XWALK_NOPRIOR ON TEDS_A.NOPRIOR = TEDS_XWALK_NOPRIOR.id
  LEFT JOIN TEDS_XWALK_PSOURCE ON TEDS_A.PSOURCE = TEDS_XWALK_PSOURCE.id
  LEFT JOIN TEDS_XWALK_ARRESTS ON TEDS_A.ARRESTS = TEDS_XWALK_ARRESTS.id 
  LEFT JOIN TEDS_XWALK_EMPLOY ON TEDS_A.EMPLOY = TEDS_XWALK_EMPLOY.id
  LEFT JOIN TEDS_XWALK_METHUSE ON TEDS_A.METHUSE = TEDS_XWALK_METHUSE.id 
  LEFT JOIN TEDS_XWALK_PSYPROB ON TEDS_A.PSYPROB = TEDS_XWALK_PSYPROB.id
  LEFT JOIN TEDS_XWALK_PREG ON TEDS_A.PREG = TEDS_XWALK_PREG.id
  LEFT JOIN TEDS_XWALK_GENDER ON TEDS_A.GENDER = TEDS_XWALK_GENDER.id
  LEFT JOIN TEDS_XWALK_VET ON TEDS_A.VET = TEDS_XWALK_VET.id
  LEFT JOIN TEDS_XWALK_LIVARAG ON TEDS_A.LIVARAG = TEDS_XWALK_LIVARAG.id
  LEFT JOIN TEDS_XWALK_DAYWAIT ON TEDS_A.DAYWAIT = TEDS_XWALK_DAYWAIT.id
  LEFT JOIN TEDS_XWALK_DSMCRIT ON TEDS_A.DSMCRIT = TEDS_XWALK_DSMCRIT.id
  LEFT JOIN TEDS_XWALK_AGE ON TEDS_A.AGE = TEDS_XWALK_AGE.id
  LEFT JOIN TEDS_XWALK_RACE ON TEDS_A.RACE = TEDS_XWALK_RACE.id
  LEFT JOIN TEDS_XWALK_ETHNIC ON TEDS_A.ETHNIC = TEDS_XWALK_ETHNIC.id
  LEFT JOIN TEDS_XWALK_DETNLF ON TEDS_A.DETNLF = TEDS_XWALK_DETNLF.id
  LEFT JOIN TEDS_XWALK_PRIMINC ON TEDS_A.PRIMINC = TEDS_XWALK_PRIMINC.id
  LEFT JOIN TEDS_XWALK_SUB1 ON TEDS_A.SUB1 = TEDS_XWALK_SUB1.id
  LEFT JOIN TEDS_XWALK_SUB2 ON TEDS_A.SUB2 = TEDS_XWALK_SUB2.id
  LEFT JOIN TEDS_XWALK_SUB3 ON TEDS_A.SUB3 = TEDS_XWALK_SUB3.id
  LEFT JOIN TEDS_XWALK_ROUTE1 ON TEDS_A.ROUTE1 = TEDS_XWALK_ROUTE1.id
  LEFT JOIN TEDS_XWALK_ROUTE2 ON TEDS_A.ROUTE2 = TEDS_XWALK_ROUTE2.id
  LEFT JOIN TEDS_XWALK_ROUTE3 ON TEDS_A.ROUTE3 = TEDS_XWALK_ROUTE3.id
  LEFT JOIN TEDS_XWALK_FREQ1 ON TEDS_A.FREQ1 = TEDS_XWALK_FREQ1.id
  LEFT JOIN TEDS_XWALK_FREQ2 ON TEDS_A.FREQ2 = TEDS_XWALK_FREQ2.id
  LEFT JOIN TEDS_XWALK_FREQ3 ON TEDS_A.FREQ3 = TEDS_XWALK_FREQ3.id
  LEFT JOIN TEDS_XWALK_FRSTUSE1 ON TEDS_A.FRSTUSE1 = TEDS_XWALK_FRSTUSE1.id
  LEFT JOIN TEDS_XWALK_FRSTUSE2 ON TEDS_A.FRSTUSE2 = TEDS_XWALK_FRSTUSE2.id
  LEFT JOIN TEDS_XWALK_FRSTUSE3 ON TEDS_A.FRSTUSE3 = TEDS_XWALK_FRSTUSE3.id
  LEFT JOIN TEDS_XWALK_HLTHINS ON TEDS_A.HLTHINS = TEDS_XWALK_HLTHINS.id
  LEFT JOIN TEDS_XWALK_PRIMPAY ON TEDS_A.PRIMPAY = TEDS_XWALK_PRIMPAY.id
  LEFT JOIN TEDS_XWALK_FREQ_ATND_SELF_HELP ON TEDS_A.FREQ_ATND_SELF_HELP = TEDS_XWALK_FREQ_ATND_SELF_HELP.id
  LEFT JOIN TEDS_XWALK_ALCFLG ON TEDS_A.ALCFLG = TEDS_XWALK_ALCFLG.id
  LEFT JOIN TEDS_XWALK_COKEFLG ON TEDS_A.COKEFLG = TEDS_XWALK_COKEFLG.id
  LEFT JOIN TEDS_XWALK_MARFLG ON TEDS_A.MARFLG = TEDS_XWALK_MARFLG.id
  LEFT JOIN TEDS_XWALK_HERFLG ON TEDS_A.HERFLG = TEDS_XWALK_HERFLG.id
  LEFT JOIN TEDS_XWALK_METHFLG ON TEDS_A.METHFLG = TEDS_XWALK_METHFLG.id
  LEFT JOIN TEDS_XWALK_OPSYNFLG ON TEDS_A.OPSYNFLG = TEDS_XWALK_OPSYNFLG.id
  LEFT JOIN TEDS_XWALK_PCPFLG ON TEDS_A.PCPFLG = TEDS_XWALK_PCPFLG.id
  LEFT JOIN TEDS_XWALK_HALLFLG ON TEDS_A.HALLFLG = TEDS_XWALK_HALLFLG.id
  LEFT JOIN TEDS_XWALK_MTHAMFLG ON TEDS_A.MTHAMFLG = TEDS_XWALK_MTHAMFLG.id
  LEFT JOIN TEDS_XWALK_AMPHFLG ON TEDS_A.AMPHFLG = TEDS_XWALK_AMPHFLG.id
  LEFT JOIN TEDS_XWALK_STIMFLG ON TEDS_A.STIMFLG = TEDS_XWALK_STIMFLG.id
  LEFT JOIN TEDS_XWALK_BENZFLG ON TEDS_A.BENZFLG = TEDS_XWALK_BENZFLG.id
  LEFT JOIN TEDS_XWALK_TRNQFLG ON TEDS_A.TRNQFLG = TEDS_XWALK_TRNQFLG.id
  LEFT JOIN TEDS_XWALK_BARBFLG ON TEDS_A.BARBFLG = TEDS_XWALK_BARBFLG.id
  LEFT JOIN TEDS_XWALK_SEDHPFLG ON TEDS_A.SEDHPFLG = TEDS_XWALK_SEDHPFLG.id
  LEFT JOIN TEDS_XWALK_INHFLG ON TEDS_A.INHFLG = TEDS_XWALK_INHFLG.id
  LEFT JOIN TEDS_XWALK_OTCFLG ON TEDS_A.OTCFLG = TEDS_XWALK_OTCFLG.id
  LEFT JOIN TEDS_XWALK_OTHERFLG ON TEDS_A.OTHERFLG = TEDS_XWALK_OTHERFLG.id
  LEFT JOIN TEDS_XWALK_DIVISION ON TEDS_A.DIVISION = TEDS_XWALK_DIVISION.id
  LEFT JOIN TEDS_XWALK_REGION ON TEDS_A.REGION = TEDS_XWALK_REGION.id
  LEFT JOIN TEDS_XWALK_IDU ON TEDS_A.IDU = TEDS_XWALK_IDU.id
  LEFT JOIN TEDS_XWALK_ALCDRUG ON TEDS_A.ALCDRUG = TEDS_XWALK_ALCDRUG.id;
-- made a table with 1,416,357 records, which is exact # of rows in the original TEDS_A table


