-- Query to convert the TEDS numeric codes to human readable format and load
-- the data in to a new table.  Must have run all the code in codebook_tables.sql first.
-- This query differs from the query found in TEDS_DOH_conversion.sql by:
--   this one uses the original column names from samhsa, the other changes the column names to match DOH.
--   this one has all the states and the other strips out any non-Hawaii entries.

-- tables to add
-- TEDS_XWALK_ARRESTS_D;
-- TEDS_XWALK_DETNLF_D
-- TEDS_XWALK_EMPLOY_D
-- TEDS_XWALK_FREQ1_D
-- TEDS_XWALK_FREQ2_D
-- TEDS_XWALK_FREQ3_D
-- TEDS_XWALK_FREQ_ATND_SELF_HELP_D
-- TEDS_XWALK_LIVARAG_D
-- TEDS_XWALK_LOS      
-- TEDS_XWALK_SERVICES_D
-- TEDS_XWALK_SUB1_D
-- TEDS_XWALK_SUB2_D
-- TEDS_XWALK_SUB3_D
-- TEDS_XWALK_REASON

-- don't have crosswalk for these, maybe in earlier or later crosswalks?
-- CBSA
-- PMSA
-- NUMSUBS

drop table if exists TEDS_D2_PART_1;
drop table if exists TEDS_D2_PART_2;
drop table if exists TEDS_D2;

-- Had to do this in 2 parts and them merge because MySQL can only handle 61 joins.
create table TEDS_D2_PART_1
select
  TEDS_D.CASEID,
  TEDS_D.DISYR, 
  TEDS_D.CBSA,
  TEDS_D.PMSA,
  TEDS_D.NUMSUBS,
  TEDS_XWALK_STFIPS.value as STFIPS,
  TEDS_XWALK_EDUC.value as EDUC,
  TEDS_XWALK_MARSTAT.value as MARSTAT,
  TEDS_XWALK_SERVICES.value as SERVICES,
  TEDS_XWALK_DETCRIM.value as DETCRIM,
  TEDS_XWALK_NOPRIOR.value as NOPRIOR,
  TEDS_XWALK_PSOURCE.value as PSOURCE, 
  TEDS_XWALK_ARRESTS.value as ARRESTS,
  TEDS_XWALK_EMPLOY.value as EMPLOY,
  TEDS_XWALK_METHUSE.value as METHUSE,
  TEDS_XWALK_PSYPROB.value as PSYPROB,
  TEDS_XWALK_PREG.value as PREG,
  TEDS_XWALK_GENDER.value as GENDER,
  TEDS_XWALK_VET.value as VET,
  TEDS_XWALK_LIVARAG.value as LIVARAG,
  TEDS_XWALK_DAYWAIT.value as DAYWAIT,
  TEDS_XWALK_DSMCRIT.value as DSMCRIT,
  TEDS_XWALK_AGE.value as AGE,
  TEDS_XWALK_RACE.value as RACE,
  TEDS_XWALK_ETHNIC.value as ETHNIC,
  TEDS_XWALK_DETNLF.value as DETNLF,
  TEDS_XWALK_PRIMINC.value as PRIMINC,
  TEDS_XWALK_SUB1.value as SUB1,
  TEDS_XWALK_SUB2.value as SUB2,
  TEDS_XWALK_SUB3.value as SUB3,
  TEDS_XWALK_ROUTE1.value as ROUTE1,
  TEDS_XWALK_ROUTE2.value as ROUTE2,
  TEDS_XWALK_ROUTE3.value as ROUTE3,
  TEDS_XWALK_FREQ1.value as FREQ1,
  TEDS_XWALK_FREQ2.value as FREQ2,
  TEDS_XWALK_FREQ3.value as FREQ3,
  TEDS_XWALK_FRSTUSE1.value as FRSTUSE1,
  TEDS_XWALK_FRSTUSE2.value as FRSTUSE2,
  TEDS_XWALK_FRSTUSE3.value as FRSTUSE3,
  TEDS_XWALK_HLTHINS.value as HLTHINS
from 
  TEDS_D
  LEFT JOIN TEDS_XWALK_STFIPS ON TEDS_D.STFIPS = TEDS_XWALK_STFIPS.id 
  LEFT JOIN TEDS_XWALK_EDUC ON TEDS_D.EDUC = TEDS_XWALK_EDUC.id
  LEFT JOIN TEDS_XWALK_MARSTAT ON TEDS_D.MARSTAT = TEDS_XWALK_MARSTAT.id
  LEFT JOIN TEDS_XWALK_SERVICES ON TEDS_D.SERVICES = TEDS_XWALK_SERVICES.id
  LEFT JOIN TEDS_XWALK_DETCRIM ON TEDS_D.DETCRIM = TEDS_XWALK_DETCRIM.id
  LEFT JOIN TEDS_XWALK_NOPRIOR ON TEDS_D.NOPRIOR = TEDS_XWALK_NOPRIOR.id
  LEFT JOIN TEDS_XWALK_PSOURCE ON TEDS_D.PSOURCE = TEDS_XWALK_PSOURCE.id
  LEFT JOIN TEDS_XWALK_ARRESTS ON TEDS_D.ARRESTS = TEDS_XWALK_ARRESTS.id 
  LEFT JOIN TEDS_XWALK_EMPLOY ON TEDS_D.EMPLOY = TEDS_XWALK_EMPLOY.id
  LEFT JOIN TEDS_XWALK_METHUSE ON TEDS_D.METHUSE = TEDS_XWALK_METHUSE.id 
  LEFT JOIN TEDS_XWALK_PSYPROB ON TEDS_D.PSYPROB = TEDS_XWALK_PSYPROB.id
  LEFT JOIN TEDS_XWALK_PREG ON TEDS_D.PREG = TEDS_XWALK_PREG.id
  LEFT JOIN TEDS_XWALK_GENDER ON TEDS_D.GENDER = TEDS_XWALK_GENDER.id
  LEFT JOIN TEDS_XWALK_VET ON TEDS_D.VET = TEDS_XWALK_VET.id
  LEFT JOIN TEDS_XWALK_LIVARAG ON TEDS_D.LIVARAG = TEDS_XWALK_LIVARAG.id
  LEFT JOIN TEDS_XWALK_DAYWAIT ON TEDS_D.DAYWAIT = TEDS_XWALK_DAYWAIT.id
  LEFT JOIN TEDS_XWALK_DSMCRIT ON TEDS_D.DSMCRIT = TEDS_XWALK_DSMCRIT.id
  LEFT JOIN TEDS_XWALK_AGE ON TEDS_D.AGE = TEDS_XWALK_AGE.id
  LEFT JOIN TEDS_XWALK_RACE ON TEDS_D.RACE = TEDS_XWALK_RACE.id
  LEFT JOIN TEDS_XWALK_ETHNIC ON TEDS_D.ETHNIC = TEDS_XWALK_ETHNIC.id
  LEFT JOIN TEDS_XWALK_DETNLF ON TEDS_D.DETNLF = TEDS_XWALK_DETNLF.id
  LEFT JOIN TEDS_XWALK_PRIMINC ON TEDS_D.PRIMINC = TEDS_XWALK_PRIMINC.id
  LEFT JOIN TEDS_XWALK_SUB1 ON TEDS_D.SUB1 = TEDS_XWALK_SUB1.id
  LEFT JOIN TEDS_XWALK_SUB2 ON TEDS_D.SUB2 = TEDS_XWALK_SUB2.id
  LEFT JOIN TEDS_XWALK_SUB3 ON TEDS_D.SUB3 = TEDS_XWALK_SUB3.id
  LEFT JOIN TEDS_XWALK_ROUTE1 ON TEDS_D.ROUTE1 = TEDS_XWALK_ROUTE1.id
  LEFT JOIN TEDS_XWALK_ROUTE2 ON TEDS_D.ROUTE2 = TEDS_XWALK_ROUTE2.id
  LEFT JOIN TEDS_XWALK_ROUTE3 ON TEDS_D.ROUTE3 = TEDS_XWALK_ROUTE3.id
  LEFT JOIN TEDS_XWALK_FREQ1 ON TEDS_D.FREQ1 = TEDS_XWALK_FREQ1.id
  LEFT JOIN TEDS_XWALK_FREQ2 ON TEDS_D.FREQ2 = TEDS_XWALK_FREQ2.id
  LEFT JOIN TEDS_XWALK_FREQ3 ON TEDS_D.FREQ3 = TEDS_XWALK_FREQ3.id
  LEFT JOIN TEDS_XWALK_FRSTUSE1 ON TEDS_D.FRSTUSE1 = TEDS_XWALK_FRSTUSE1.id
  LEFT JOIN TEDS_XWALK_FRSTUSE2 ON TEDS_D.FRSTUSE2 = TEDS_XWALK_FRSTUSE2.id
  LEFT JOIN TEDS_XWALK_FRSTUSE3 ON TEDS_D.FRSTUSE3 = TEDS_XWALK_FRSTUSE3.id
  LEFT JOIN TEDS_XWALK_HLTHINS ON TEDS_D.HLTHINS = TEDS_XWALK_HLTHINS.id
WHERE TEDS_D.DISYR != '2021';
-- made a table with 131,305 records, which is exact # of rows in the original TEDS_D table

-- Had to do this in 2 parts and them merge because MySQL can only handle 61 joins.
create table TEDS_D2_PART_2
select
  TEDS_D.CASEID,
  TEDS_XWALK_PRIMPAY.value as PRIMPAY,
  TEDS_XWALK_FREQ_ATND_SELF_HELP.value as FREQ_ATND_SELF_HELP,
  TEDS_XWALK_ALCFLG.value as ALCFLG,
  TEDS_XWALK_COKEFLG.value as COKEFLG,
  TEDS_XWALK_MARFLG.value as MARFLG,
  TEDS_XWALK_HERFLG.value as HERFLG,
  TEDS_XWALK_METHFLG.value as METHFLG,
  TEDS_XWALK_OPSYNFLG.value as OPSYNFLG,
  TEDS_XWALK_PCPFLG.value as PCPFLG,
  TEDS_XWALK_HALLFLG.value as HALLFLG,
  TEDS_XWALK_MTHAMFLG.value as MTHAMFLG,
  TEDS_XWALK_AMPHFLG.value as AMPHFLG,
  TEDS_XWALK_STIMFLG.value as STIMFLG,
  TEDS_XWALK_BENZFLG.value as BENZFLG,
  TEDS_XWALK_TRNQFLG.value as TRNQFLG,
  TEDS_XWALK_BARBFLG.value as BARBFLG,
  TEDS_XWALK_SEDHPFLG.value as SEDHPFLG,
  TEDS_XWALK_INHFLG.value as INHFLG,
  TEDS_XWALK_OTCFLG.value as OTCFLG,
  TEDS_XWALK_OTHERFLG.value as OTHERFLG,
  TEDS_XWALK_DIVISION.value as DIVISION,
  TEDS_XWALK_REGION.value as REGION,
  TEDS_XWALK_IDU.value as IDU,
  TEDS_XWALK_ALCDRUG.value as ALCDRUG,
  -- new additions
  TEDS_XWALK_ARRESTS_D.value as ARRESTS_D,
  TEDS_XWALK_DETNLF_D.value as DETNLF_D,
  TEDS_XWALK_EMPLOY_D.value as EMPLOY_D,
  TEDS_XWALK_FREQ1_D.value as FREQ1_D,
  TEDS_XWALK_FREQ2_D.value as FREQ2_D,
  TEDS_XWALK_FREQ3_D.value as FREQ3_D,
  TEDS_XWALK_FREQ_ATND_SELF_HELP_D.value as FREQ_ATND_SELF_HELP_D,
  TEDS_XWALK_LIVARAG_D.value as LIVARAG_D,
  TEDS_XWALK_LOS.value as LOS,
  TEDS_XWALK_SERVICES_D.value as SERVICES_D,
  TEDS_XWALK_SUB1_D.value as SUB1_D,
  TEDS_XWALK_SUB2_D.value as SUB2_D,
  TEDS_XWALK_SUB3_D.value as SUB3_D,
  TEDS_XWALK_REASON.value as REASON
from 
  TEDS_D
  LEFT JOIN TEDS_XWALK_PRIMPAY ON TEDS_D.PRIMPAY = TEDS_XWALK_PRIMPAY.id
  LEFT JOIN TEDS_XWALK_FREQ_ATND_SELF_HELP ON TEDS_D.FREQ_ATND_SELF_HELP = TEDS_XWALK_FREQ_ATND_SELF_HELP.id
  LEFT JOIN TEDS_XWALK_ALCFLG ON TEDS_D.ALCFLG = TEDS_XWALK_ALCFLG.id
  LEFT JOIN TEDS_XWALK_COKEFLG ON TEDS_D.COKEFLG = TEDS_XWALK_COKEFLG.id
  LEFT JOIN TEDS_XWALK_MARFLG ON TEDS_D.MARFLG = TEDS_XWALK_MARFLG.id
  LEFT JOIN TEDS_XWALK_HERFLG ON TEDS_D.HERFLG = TEDS_XWALK_HERFLG.id
  LEFT JOIN TEDS_XWALK_METHFLG ON TEDS_D.METHFLG = TEDS_XWALK_METHFLG.id
  LEFT JOIN TEDS_XWALK_OPSYNFLG ON TEDS_D.OPSYNFLG = TEDS_XWALK_OPSYNFLG.id
  LEFT JOIN TEDS_XWALK_PCPFLG ON TEDS_D.PCPFLG = TEDS_XWALK_PCPFLG.id
  LEFT JOIN TEDS_XWALK_HALLFLG ON TEDS_D.HALLFLG = TEDS_XWALK_HALLFLG.id
  LEFT JOIN TEDS_XWALK_MTHAMFLG ON TEDS_D.MTHAMFLG = TEDS_XWALK_MTHAMFLG.id
  LEFT JOIN TEDS_XWALK_AMPHFLG ON TEDS_D.AMPHFLG = TEDS_XWALK_AMPHFLG.id
  LEFT JOIN TEDS_XWALK_STIMFLG ON TEDS_D.STIMFLG = TEDS_XWALK_STIMFLG.id
  LEFT JOIN TEDS_XWALK_BENZFLG ON TEDS_D.BENZFLG = TEDS_XWALK_BENZFLG.id
  LEFT JOIN TEDS_XWALK_TRNQFLG ON TEDS_D.TRNQFLG = TEDS_XWALK_TRNQFLG.id
  LEFT JOIN TEDS_XWALK_BARBFLG ON TEDS_D.BARBFLG = TEDS_XWALK_BARBFLG.id
  LEFT JOIN TEDS_XWALK_SEDHPFLG ON TEDS_D.SEDHPFLG = TEDS_XWALK_SEDHPFLG.id
  LEFT JOIN TEDS_XWALK_INHFLG ON TEDS_D.INHFLG = TEDS_XWALK_INHFLG.id
  LEFT JOIN TEDS_XWALK_OTCFLG ON TEDS_D.OTCFLG = TEDS_XWALK_OTCFLG.id
  LEFT JOIN TEDS_XWALK_OTHERFLG ON TEDS_D.OTHERFLG = TEDS_XWALK_OTHERFLG.id
  LEFT JOIN TEDS_XWALK_DIVISION ON TEDS_D.DIVISION = TEDS_XWALK_DIVISION.id
  LEFT JOIN TEDS_XWALK_REGION ON TEDS_D.REGION = TEDS_XWALK_REGION.id
  LEFT JOIN TEDS_XWALK_IDU ON TEDS_D.IDU = TEDS_XWALK_IDU.id
  LEFT JOIN TEDS_XWALK_ALCDRUG ON TEDS_D.ALCDRUG = TEDS_XWALK_ALCDRUG.id
  LEFT JOIN TEDS_XWALK_ARRESTS_D ON TEDS_D.ARRESTS_D = TEDS_XWALK_ARRESTS_D.id
  LEFT JOIN TEDS_XWALK_DETNLF_D ON TEDS_D.DETNLF_D = TEDS_XWALK_DETNLF_D.id
  LEFT JOIN TEDS_XWALK_EMPLOY_D ON TEDS_D.EMPLOY_D = TEDS_XWALK_EMPLOY_D.id
  LEFT JOIN TEDS_XWALK_FREQ1_D ON TEDS_D.FREQ1_D = TEDS_XWALK_FREQ1_D.id
  LEFT JOIN TEDS_XWALK_FREQ2_D ON TEDS_D.FREQ2_D = TEDS_XWALK_FREQ2_D.id
  LEFT JOIN TEDS_XWALK_FREQ3_D ON TEDS_D.FREQ3_D = TEDS_XWALK_FREQ3_D.id
  LEFT JOIN TEDS_XWALK_FREQ_ATND_SELF_HELP_D ON TEDS_D.FREQ_ATND_SELF_HELP_D = TEDS_XWALK_FREQ_ATND_SELF_HELP_D.id
  LEFT JOIN TEDS_XWALK_LIVARAG_D ON TEDS_D.LIVARAG_D = TEDS_XWALK_LIVARAG_D.id
  LEFT JOIN TEDS_XWALK_LOS ON TEDS_D.LOS = TEDS_XWALK_LOS.id
  LEFT JOIN TEDS_XWALK_SERVICES_D ON TEDS_D.SERVICES_D = TEDS_XWALK_SERVICES_D.id
  LEFT JOIN TEDS_XWALK_SUB1_D ON TEDS_D.SUB1_D = TEDS_XWALK_SUB1_D.id
  LEFT JOIN TEDS_XWALK_SUB2_D ON TEDS_D.SUB2_D = TEDS_XWALK_SUB2_D.id
  LEFT JOIN TEDS_XWALK_SUB3_D ON TEDS_D.SUB3_D = TEDS_XWALK_SUB3_D.id
  LEFT JOIN TEDS_XWALK_REASON ON TEDS_D.REASON = TEDS_XWALK_REASON.id
WHERE TEDS_D.DISYR != '2021';
-- made a table with 131,305 records, which is exact # of rows in the original TEDS_D table

-- This is the merge of the 2 above tables.  Had to handle in 2 parts because MySQL can only handle 61 joins.
create table TEDS_D2
SELECT
  TEDS_D2_PART_1.CASEID,
  TEDS_D2_PART_1.DISYR, 
  TEDS_D2_PART_1.CBSA,
  TEDS_D2_PART_1.PMSA,
  TEDS_D2_PART_1.NUMSUBS,
  TEDS_D2_PART_1.STFIPS,
  TEDS_D2_PART_1.EDUC,
  TEDS_D2_PART_1.MARSTAT,
  TEDS_D2_PART_1.SERVICES,
  TEDS_D2_PART_1.DETCRIM,
  TEDS_D2_PART_1.NOPRIOR,
  TEDS_D2_PART_1.PSOURCE, 
  TEDS_D2_PART_1.ARRESTS,
  TEDS_D2_PART_1.EMPLOY,
  TEDS_D2_PART_1.METHUSE,
  TEDS_D2_PART_1.PSYPROB,
  TEDS_D2_PART_1.PREG,
  TEDS_D2_PART_1.GENDER,
  TEDS_D2_PART_1.VET,
  TEDS_D2_PART_1.LIVARAG,
  TEDS_D2_PART_1.DAYWAIT,
  TEDS_D2_PART_1.DSMCRIT,
  TEDS_D2_PART_1.AGE,
  TEDS_D2_PART_1.RACE,
  TEDS_D2_PART_1.ETHNIC,
  TEDS_D2_PART_1.DETNLF,
  TEDS_D2_PART_1.PRIMINC,
  TEDS_D2_PART_1.SUB1,
  TEDS_D2_PART_1.SUB2,
  TEDS_D2_PART_1.SUB3,
  TEDS_D2_PART_1.ROUTE1,
  TEDS_D2_PART_1.ROUTE2,
  TEDS_D2_PART_1.ROUTE3,
  TEDS_D2_PART_1.FREQ1,
  TEDS_D2_PART_1.FREQ2,
  TEDS_D2_PART_1.FREQ3,
  TEDS_D2_PART_1.FRSTUSE1,
  TEDS_D2_PART_1.FRSTUSE2,
  TEDS_D2_PART_1.FRSTUSE3,
  TEDS_D2_PART_1.HLTHINS,
  TEDS_D2_PART_2.PRIMPAY,
  TEDS_D2_PART_2.FREQ_ATND_SELF_HELP,
  TEDS_D2_PART_2.ALCFLG,
  TEDS_D2_PART_2.COKEFLG,
  TEDS_D2_PART_2.MARFLG,
  TEDS_D2_PART_2.HERFLG,
  TEDS_D2_PART_2.METHFLG,
  TEDS_D2_PART_2.OPSYNFLG,
  TEDS_D2_PART_2.PCPFLG,
  TEDS_D2_PART_2.HALLFLG,
  TEDS_D2_PART_2.MTHAMFLG,
  TEDS_D2_PART_2.AMPHFLG,
  TEDS_D2_PART_2.STIMFLG,
  TEDS_D2_PART_2.BENZFLG,
  TEDS_D2_PART_2.TRNQFLG,
  TEDS_D2_PART_2.BARBFLG,
  TEDS_D2_PART_2.SEDHPFLG,
  TEDS_D2_PART_2.INHFLG,
  TEDS_D2_PART_2.OTCFLG,
  TEDS_D2_PART_2.OTHERFLG,
  TEDS_D2_PART_2.DIVISION,
  TEDS_D2_PART_2.REGION,
  TEDS_D2_PART_2.IDU,
  TEDS_D2_PART_2.ALCDRUG,
  TEDS_D2_PART_2.ARRESTS_D,
  TEDS_D2_PART_2.DETNLF_D,
  TEDS_D2_PART_2.EMPLOY_D,
  TEDS_D2_PART_2.FREQ1_D,
  TEDS_D2_PART_2.FREQ2_D,
  TEDS_D2_PART_2.FREQ3_D,
  TEDS_D2_PART_2.FREQ_ATND_SELF_HELP_D,
  TEDS_D2_PART_2.LIVARAG_D,
  TEDS_D2_PART_2.LOS,
  TEDS_D2_PART_2.SERVICES_D,
  TEDS_D2_PART_2.SUB1_D,
  TEDS_D2_PART_2.SUB2_D,
  TEDS_D2_PART_2.SUB3_D,
  TEDS_D2_PART_2.REASON
FROM
    TEDS_D2_PART_1
    INNER JOIN TEDS_D2_PART_2
      ON TEDS_D2_PART_1.CASEID = TEDS_D2_PART_2.CASEID
UNION
SELECT
  TEDS_D.CASEID,
  TEDS_D.DISYR, 
  TEDS_D.CBSA,
  TEDS_D.PMSA,
  TEDS_D.NUMSUBS,
  TEDS_D.STFIPS,
  TEDS_D.EDUC,
  TEDS_D.MARSTAT,
  TEDS_D.SERVICES,
  TEDS_D.DETCRIM,
  TEDS_D.NOPRIOR,
  TEDS_D.PSOURCE, 
  TEDS_D.ARRESTS,
  TEDS_D.EMPLOY,
  TEDS_D.METHUSE,
  TEDS_D.PSYPROB,
  TEDS_D.PREG,
  TEDS_D.GENDER,
  TEDS_D.VET,
  TEDS_D.LIVARAG,
  TEDS_D.DAYWAIT,
  TEDS_D.DSMCRIT,
  TEDS_D.AGE,
  TEDS_D.RACE,
  TEDS_D.ETHNIC,
  TEDS_D.DETNLF,
  TEDS_D.PRIMINC,
  TEDS_D.SUB1,
  TEDS_D.SUB2,
  TEDS_D.SUB3,
  TEDS_D.ROUTE1,
  TEDS_D.ROUTE2,
  TEDS_D.ROUTE3,
  TEDS_D.FREQ1,
  TEDS_D.FREQ2,
  TEDS_D.FREQ3,
  TEDS_D.FRSTUSE1,
  TEDS_D.FRSTUSE2,
  TEDS_D.FRSTUSE3,
  TEDS_D.HLTHINS,
  TEDS_D.PRIMPAY,
  TEDS_D.FREQ_ATND_SELF_HELP,
  TEDS_D.ALCFLG,
  TEDS_D.COKEFLG,
  TEDS_D.MARFLG,
  TEDS_D.HERFLG,
  TEDS_D.METHFLG,
  TEDS_D.OPSYNFLG,
  TEDS_D.PCPFLG,
  TEDS_D.HALLFLG,
  TEDS_D.MTHAMFLG,
  TEDS_D.AMPHFLG,
  TEDS_D.STIMFLG,
  TEDS_D.BENZFLG,
  TEDS_D.TRNQFLG,
  TEDS_D.BARBFLG,
  TEDS_D.SEDHPFLG,
  TEDS_D.INHFLG,
  TEDS_D.OTCFLG,
  TEDS_D.OTHERFLG,
  TEDS_D.DIVISION,
  TEDS_D.REGION,
  TEDS_D.IDU,
  TEDS_D.ALCDRUG,
  TEDS_D.ARRESTS_D,
  TEDS_D.DETNLF_D,
  TEDS_D.EMPLOY_D,
  TEDS_D.FREQ1_D,
  TEDS_D.FREQ2_D,
  TEDS_D.FREQ3_D,
  TEDS_D.FREQ_ATND_SELF_HELP_D,
  TEDS_D.LIVARAG_D,
  TEDS_D.LOS,
  TEDS_D.SERVICES_D,
  TEDS_D.SUB1_D,
  TEDS_D.SUB2_D,
  TEDS_D.SUB3_D,
  TEDS_D.REASON
FROM
    TEDS_D
WHERE DISYR = '2021';
-- made a table with 131,305 records, which is exact # of rows in the original TEDS_D table

-- don't need these anymore
-- drop table if exists TEDS_D2_PART_1;
-- drop table if exists TEDS_D2_PART_2;